-- this file was generated by `seamstress create-script`

print("welcome to seamstress from your new script!")
print("if seamstress just created this file,")
print("why not open it in a text editor now?")
print("seamstress will reload with the new script when you save the file!")

-- seamstress will call this function to start your script!
function init()
  print("this message came from within the init() function!")
  redraw()
end

local r = 168
local g = 35
local b = 60
local color = "red"

-- this function will draw some things to the screen
function redraw()
  screen.clear()
  screen.color(r, g, b)
  screen.move(screen.width / 2, 20)
  screen.text_center("this text is " .. color .. "!")
  screen.refresh()
end

-- react to clicking on the seamstress window!
function screen.click(x, y, state, button)
  print("clicked!", x, y, state, button)
  if state == 0 then
    color = "blue"
    r = 25
    b = 200
    redraw()
  end
end
