name: Build artifacts

on:
  # release:
  #   types: [published]
  push:
    tags:
      - '*.*.*'

  workflow_dispatch:

jobs:
  linux-x86_64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - name: build seamstress
        run: |
          bash ci/ubuntu.sh
      - name: zip artifact
        run: |
          cd zig-out/ && tar -czvf ../seamstress-linux-${{ github.ref_name }}.tar.gz .
      - uses: actions/upload-artifact@v2
        with:
          name: linux-${{ github.ref_name }}
          path: |
            ./*.tar.gz
  macos-x86_64:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - name: build seamstress
        run: |
          bash ci/macos-11.sh
      - name: zip artifact
        run: |
          cd zig-out/ && zip -r9 ../seamstress-macos-x86_64-${{ github.ref_name }}.zip .
      - uses: actions/upload-artifact@v2
        with:
          name: macos-x86_64-${{ github.ref_name }}
          path: |
            ./*.zip
  release:
    needs: |
      linux-x86_64
      macos-x86_64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          path: .
      - uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          draft: true
          files: |
            ./*.zip
            ./*.tar.gz
