name: Draft release

# Only trigger, when the build workflow succeeded
on:
  workflow_run:
    workflows: ["Build artifacts"]
    types:
      - completed

jobs:
  release:
    needs: |
      linux-x86_64
      macos-x86_64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          path: .
      - uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          draft: true
          files: |
            ./*.zip
            ./*.tar.gz
